[theme]
primaryColor = "#2f9e41"
backgroundColor = "#f6f3ec"
secondaryBackgroundColor = "#ffffff"
textColor = "#1c1c1c"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
